# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here
np.version.version

'1.21.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
a = np.random.random((2,3,5))
print(a.shape)
a

(2, 3, 5)


array([[[0.35145949, 0.13167707, 0.799513  , 0.68329956, 0.04118847],
        [0.03736699, 0.3170294 , 0.82562355, 0.27164343, 0.68226034],
        [0.63966307, 0.22830573, 0.5894511 , 0.79210129, 0.71856621]],

       [[0.81355045, 0.27737818, 0.83168545, 0.37644467, 0.15921749],
        [0.85799881, 0.95730929, 0.38699422, 0.76248785, 0.94796996],
        [0.398363  , 0.91659881, 0.50034867, 0.94891807, 0.73467954]]])

In [14]:
# Method 2
np.random.rand(2,3,5)

array([[[0.66742959, 0.99201289, 0.21750486, 0.95144937, 0.78234189],
        [0.76372966, 0.78612426, 0.47286028, 0.92196162, 0.95037099],
        [0.62395272, 0.71379757, 0.9437352 , 0.45693686, 0.34420641]],

       [[0.04743347, 0.24205769, 0.93444755, 0.95046604, 0.08688299],
        [0.47052263, 0.74169639, 0.23414731, 0.72044282, 0.20113618],
        [0.93037582, 0.50785373, 0.89475891, 0.30884897, 0.75877552]]])

In [25]:
# Method 3
a = np.random.randint(100, size=(2, 3, 5))
print(a)

[[[80 57 92  7  9]
  [25 50 50 85 28]
  [57 74 71 71  7]]

 [[87 77  0 36 94]
  [98 18 65 57  6]
  [15  7 60 85 47]]]


#### 4. Print *a*.


In [26]:
# your code here
a

array([[[80, 57, 92,  7,  9],
        [25, 50, 50, 85, 28],
        [57, 74, 71, 71,  7]],

       [[87, 77,  0, 36, 94],
        [98, 18, 65, 57,  6],
        [15,  7, 60, 85, 47]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [29]:
# your code 
b = np.ones((5,2,3))
b.shape

(5, 2, 3)

#### 6. Print *b*.


In [30]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here
if a.shape == b.shape:
    print('Same shape')
else: 
    print('different shape')

different shape


#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
# your answer here
np.add(a, b) # no se pueden unir por que tienen unas dimensiones diferentes (2,3,5) y (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
# your code here
c = np.transpose(b) #
c.shape #La dimensión de la transpuesta no es 2x3x5 si no 3x2x5

(3, 2, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [41]:
# your code/answer here 
np.add(a, c) #sigue sin poderse, habría que hacer un reshape

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [44]:
c = np.reshape(b, (2,3,5))

In [46]:
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [52]:
# your code/answer here 
print(a)
print(d) #Si, se ha sumado 1 a todos los valores de la matriz a.

[[[80 57 92  7  9]
  [25 50 50 85 28]
  [57 74 71 71  7]]

 [[87 77  0 36 94]
  [98 18 65 57  6]
  [15  7 60 85 47]]]
[[[81. 58. 93.  8. 10.]
  [26. 51. 51. 86. 29.]
  [58. 75. 72. 72.  8.]]

 [[88. 78.  1. 37. 95.]
  [99. 19. 66. 58.  7.]
  [16.  8. 61. 86. 48.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [50]:
# your code here
e = np.multiply (a,c)
e

array([[[80., 57., 92.,  7.,  9.],
        [25., 50., 50., 85., 28.],
        [57., 74., 71., 71.,  7.]],

       [[87., 77.,  0., 36., 94.],
        [98., 18., 65., 57.,  6.],
        [15.,  7., 60., 85., 47.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#Si, por que se han multiplicado los valores de a por 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [57]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [60]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [84]:
# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

[[[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  75.   0.  25.  75.]
  [100.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]
[[[81. 58. 93.  8. 10.]
  [26. 51. 51. 86. 29.]
  [58. 75. 72. 72.  8.]]

 [[88. 78.  1. 37. 95.]
  [99. 19. 66. 58.  7.]
  [16.  8. 61. 86. 48.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [85]:
# your code here
print (f)
print (d)

[[[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  75.   0.  25.  75.]
  [100.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]
[[[81. 58. 93.  8. 10.]
  [26. 51. 51. 86. 29.]
  [58. 75. 72. 72.  8.]]

 [[88. 78.  1. 37. 95.]
  [99. 19. 66. 58.  7.]
  [16.  8. 61. 86. 48.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.